# Generated by Django 3.2 on 2022-09-09 12:54

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0002_category_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='opening_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default=('Lundi', 'Lundi'), max_length=51),
        ),
        migrations.AddField(
            model_name='stand',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR'),
        ),
    ]
