# Generated by Django 3.2 on 2022-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0005_remove_market_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
