# Generated by Django 3.2 on 2022-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0006_auto_20220912_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='postcode',
            field=models.IntegerField(default=95200),
            preserve_default=False,
        ),
    ]
