# Generated by Django 3.2 on 2022-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0007_market_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='city',
            field=models.CharField(default='Paris', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='country',
            field=models.CharField(default='France', max_length=100),
            preserve_default=False,
        ),
    ]
