# Generated by Django 3.2 on 2022-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0008_auto_20220912_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='latitude',
            field=models.CharField(default=(12, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='longitude',
            field=models.CharField(default=(12, 12), max_length=200),
            preserve_default=False,
        ),
    ]
