# Generated by Django 3.2 on 2022-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0009_auto_20220912_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
