# Generated by Django 3.2 on 2022-09-19 11:35

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marche_nomade', '0011_alter_market_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='closing_hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stand',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stand',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stand',
            name='opening_hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stand',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='FR'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
