import React, {useState, useEffect} from 'react'
import AuthContext from '../context/AuthContext'
import { Link, useParams } from 'react-router-dom'
import axios from 'axios'
import '../css/market.css'
import ReactTooltip from 'react-tooltip'
import MarketBackground from "../assets/market-background.jpeg"
import ImageMap from "image-map";


const MarketPage = () => {
  ImageMap('img[usemap]')
  const {marketID} = useParams()
  let [market, setMarket] = useState([])

  const map_coordinates = [ 
    "168,240,22",
    "197,366,33",
    "302,395,30",
    "426,426,30",
    "533,474,30",
    "215,282,34",
    "280,303,34",
    "348,320,34",
    "399,342,34",
    "474,365,34",
    "571,405,34",
    "558,349,34",
    "618,367,34",
    "734,351,50",
    "637,249,69",
    "487,179,60",
    "388,175,36",
    "420,117,36",
    "214,168,36",
    "288,117,36",
    "242,82,36",
    "279,33,36",
    "330,45,36",
    "609,39,36",
    "672,61,36",
    "731,72,36",
    "874,119,54",
    "962,146,36",
  ]

  useEffect(() => {
    getSingleMarket()
  }, [])


  let getSingleMarket = async() => {
    let response = await axios.get(`http://127.0.0.1:8000/marche_nomade/markets/${marketID}`)
    if(response.status === 200){
      setMarket(response.data)
    }
  }
  let stands = market.stands
  return (
    <div className='market-home'>

      {/* <!-- Image Map Generated by http://www.image-map.net/ --> */}
      <img alt='market background' src={MarketBackground} useMap="#image-map" className='image-map-src'/>
        <map name="image-map" className='map'>
          {stands?.map((stand, idx) => 
            (
              <>
              <area className='map-area' target="_self" alt={stand.name} title={stand.name} href={`http://localhost:3000/stand/${stand.id}`} coords={map_coordinates[idx]} shape="circle">
              </area>
              </>
              )
              )}
        </map>
    </div>
    
  )
}

export default MarketPage

      {/* <h1>
          Mon marché: {market.name}
      </h1>
      <h2>Les stands</h2>
      <ul>
        {stands?.map(stand => 
        (
          <li key={stand.id} data-tip data-for={`marker-stand-${stand.id}`}>
          <Link to={`/stand/${stand.id}`}>
            <img src="https://img.icons8.com/color/48/000000/marker--v1.png"/>
            <ReactTooltip id={`marker-stand-${stand.id}`}>
              <h1>{stand.name}</h1>
            </ReactTooltip>
          </Link>
          </li>
        )
        )}
      </ul> */}


